version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/Desktop/postgres-databases/vouch-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db




# ------------------------------------------------------------------------------|
# run : docker compose up -d                                                 |
# ------------------------------------------------------------------------------|
# connection string : postgresql://vouch:root@localhost:5432/postgres          |
# ------------------------------------------------------------------------------|